const enUS = {
  "welcome": "Welcome to\nUno To Do!",
  "start": "Start using the best To Do app",
  "get_started": "Get started",
  "important": "Important",
  "tasks": "Tasks",
  "new_list": "New List",
  "enter_list_title": "Enter list title",
  "create": "Create",
  "cancel": "Cancel",
  "todo": "To Do",
  "completed": "Completed",
  "loading": "Loading...",
  "add_task": "Add a task",
  "rename_list": "Rename list",
  "rename": "Rename",
  "search": "Search",
  "delete": "Delete",
  "are_you_sure": "Are you sure?",
  "list_deleted": "List will be permanently deleted",
  "important_tasks": "Important Tasks",
  "try_starring": "Try starring some tasks to see them here.",
  "search_for_task": "Search for tasks",
  "would_you_like": "What task would you like to find?",
  "task_not_found": "Task not found",
  "could_not_find": "We searched high and low but couldn't find\nwhat you're looking for",
  "settings": "Settings",
  "general": "General",
  "purple": "Purple",
  "blue": "Blue",
  "yellow": "Yellow",
  "color_palette": "Color palette",
  "language": "Language",
  "english": "English",
  "russian": "Russian",
  "uzbek": "Uzbek",
  "change_restart": "Change will be applied at next app restart",
  "mode": "Mode",
  "light": "Light",
  "dark": "Dark",
  "about": "About",
  "version": "Version",
  "sign_out": "Sign out",
  "sign_in": "Sign in",
  "sign_up": "Sign up",
  "would_like_to_sign_out": "Are you sure you would like to sign out?",
  "due": "Due",
  "today": "Today",
  "tomorrow": "Tomorrow",
  "next_week": "Next Week",
  "pick_date": "Pick a Date",
  "task_name": "Task Name",
  "completed_today": "Completed today",
  "note": "Note",
};